import Head from 'next/head'
//styles
import styles from '../styles/Home.module.scss';
//components
import Header from '../components/header/Header';
import Banner from '../components/banner/Banner';
import PickYourTrip from '../components/pickYourTrip/PickYourTrip';
import Value from '../components/values';
import Us from '../components/us';
import Contact from '../components/contact';
import Proyects from '../components/proyects';
import Footer from '../components/footer';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>HippoSoft | Let's Create</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Header />
                <Banner />
                <PickYourTrip />
                <Value />
                <Us />
                <Proyects />
                <Contact />
            </main>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </div>
    )
}
